#!/usr/bin/env python

import smbuilder.builder
import smbuilder.parser

import argparse
import os
import shutil


def clean():
    if os.path.exists(smbuilder.builder.OUTPUT_DIR):
        shutil.rmtree(smbuilder.builder.OUTPUT_DIR)


def main():
    parser = argparse.ArgumentParser(
        description='A sourcemod build and packaging tool.')
    parser.add_argument('target', nargs='?')
    parser.add_argument('-c', '--compiler', default='spcomp',
                        help='Sourcepawn compiler to use.')
    parser.add_argument('--filelist', action='store_true')
    args = parser.parse_args()

    if not args.target:
        args.target ='.'

    if args.target == 'clean':
        clean()
    else:
        builder.perform_builds(args.target, args.compiler, args.filelist)


if __name__ == '__main__':
    main()
